# Generated by Django 4.2.7 on 2025-12-03 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL of webpage to monitor', max_length=2048)),
                ('keyword', models.CharField(help_text='Keyword or phrase to search for', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active - Actively monitoring'), ('paused', 'Paused - Monitoring paused'), ('stopped', 'Stopped - No longer monitoring'), ('error', 'Error - Last check failed')], default='active', help_text='Current monitoring status', max_length=20)),
                ('last_checked_time', models.DateTimeField(blank=True, help_text='When the URL was last checked', null=True)),
                ('last_found_time', models.DateTimeField(blank=True, help_text='When keyword was last found', null=True)),
                ('check_interval_days', models.PositiveIntegerField(default=1, help_text='How often to check (in days)')),
                ('alert_email', models.BooleanField(default=True, help_text='Send email alert when keyword found')),
                ('alert_sms', models.BooleanField(default=False, help_text='Send SMS alert when keyword found')),
                ('notes', models.TextField(blank=True, help_text='User notes about this monitor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this monitor', on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('keyword_found', models.BooleanField(help_text='Whether keyword was found in page content')),
                ('page_title', models.CharField(blank=True, help_text='Title of the webpage', max_length=255)),
                ('page_excerpt', models.TextField(blank=True, help_text='Excerpt of page content where keyword was found')),
                ('http_status', models.IntegerField(blank=True, help_text='HTTP response status code', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if check failed')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Time taken to fetch and process page (milliseconds)', null=True)),
                ('monitor', models.ForeignKey(help_text='Monitor this check belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='monitoring.monitor')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('keyword_found', 'Keyword Found Alert'), ('check_failed', 'Check Failed Alert'), ('subscription_expiring', 'Subscription Expiring'), ('payment_failed', 'Payment Failed')], max_length=30)),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both Email and SMS')], default='email', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, help_text='External service ID (Twilio SID, SendGrid message ID, etc.)', max_length=255)),
                ('monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='monitoring.monitor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='monitoring__user_id_cf3af3_idx'), models.Index(fields=['notification_type'], name='monitoring__notific_9e78a3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='monitor',
            index=models.Index(fields=['user', 'status'], name='monitoring__user_id_ea76ff_idx'),
        ),
        migrations.AddIndex(
            model_name='monitor',
            index=models.Index(fields=['last_checked_time'], name='monitoring__last_ch_299cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='monitor',
            index=models.Index(fields=['status'], name='monitoring__status_ba861c_idx'),
        ),
        migrations.AddIndex(
            model_name='checkresult',
            index=models.Index(fields=['monitor', 'checked_at'], name='monitoring__monitor_3fe451_idx'),
        ),
        migrations.AddIndex(
            model_name='checkresult',
            index=models.Index(fields=['keyword_found'], name='monitoring__keyword_0b4a9e_idx'),
        ),
    ]
